name: Ejecutar scraping y actualizar CSV

on:
  schedule:
    - cron: '0 6 * * *'  # Todos los días a las 06:00 UTC
  workflow_dispatch:      # También puedes lanzarlo manualmente

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script de scraping
      run: python main_scraping.py --usar_scraping

    - name: Subir CSV actualizado al repositorio
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add licitaciones.csv
        git commit -m "Actualizar CSV automáticamente"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
